In [1]:
import numpy as np

my_array =  np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
np.floor(my_array)         #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [2]:
np.ceil(my_array)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
np.rint(my_array)

array([ 1.,  2.,  3.,  4.,  6.,  7.,  8.,  9., 10.])

In [4]:
np.array([[2,3],[28,2]])                          


array([[ 2,  3],
       [28,  2]])

In [ ]:
np.array(list(map(int,input().split())))

array([2, 8])

In [ ]:
matrix_of_row_col= np.array(list(map(int,input().split())))
first_matrix=np.array(list(map(int,input().split())))
second_matrix=np.array(list(map(int,input().split())))
final_matrix=[first_matrix,second_matrix]


In [ ]:
mat_size=np.array(list(map(int,input().split())))
f_mat=[]
for i in range((mat_size[0])):
    f_mat.append(np.array(list(map(int,input().split()))))

f_mat=np.array(f_mat)


In [ ]:
f_mat

array([[ 3, 29],
       [29,  3]])

In [ ]:
res=int(np.prod(np.sum(np.array(f_mat),axis=0)))
res

1024

In [ ]:
input()

'2'

In [2]:
import numpy as np
mat_size=np.array(list(map(int,input().split())))

In [10]:
list(map(int,input().split()))

[8, 3]

In [3]:
mat_size

array([2, 8])

In [11]:
np.array([  list(map(int,input().split())) for i in range(mat_size[0])])

array([[ 3, 82],
       [ 9,  1]])

In [ ]:
N, M = map(int, raw_input().split())

my_array = numpy.array([ map(int, raw_input().split()) for i in range(N) ])
print numpy.prod( numpy.sum( my_array, axis = 0 ) )

In [12]:
import numpy as np 
mat_size=list(map(int,input().split()))
mat=np.array([ list(map(int,input().split())) for i in range(mat_size[0])])
print(np.mean(mat,axis=1))
print(np.var(mat,axis=0))
print(np.std(mat))

[2.5 5. ]
[9.   0.25]
2.48746859276655
